site_name: Stub Generator
repo_url: https://github.com/Safe-DS/Stub-Generator
repo_name: Safe-DS/Stub-Generator
edit_uri: edit/main/docs/
site_url: !ENV READTHEDOCS_CANONICAL_URL
strict: true

nav:
  - Home:
    - README.md
    - Changelog: CHANGELOG.md
  - Development:
    - Environment: development/environment.md
    - Project Guidelines: development/project_guidelines.md
    - Contributing 🌐: https://github.com/Safe-DS/Stub-Generator/contribute

# Configuration of MkDocs & Material for MkDocs --------------------------------

theme:
  name: material
  logo: https://raw.githubusercontent.com/Safe-DS/.github/main/branding/safe-ds_logo_rounded.svg
  favicon: https://raw.githubusercontent.com/Safe-DS/.github/main/branding/safe-ds_logo_rounded.svg
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: indigo
      accent: indigo

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: black
      accent: indigo
  features:
    - content.code.copy
    - navigation.tabs
    - content.tabs.link
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top

plugins:
  - glightbox
  - search

watch:
  - src

markdown_extensions:
  # Admonitions
  - admonition
  - pymdownx.details

  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  # Diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # Footnotes
  - footnotes

  # Keys
  - pymdownx.keys

  # Icons & emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # Images
  - attr_list
  - md_in_html

  # Lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  # MathJax
  - pymdownx.arithmatex:
      generic: true

  # Permalinks
  - toc:
      permalink: true

  # Tabs
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
